#!/usr/bin/env bash
# Show domain information

dom_info() {
	local domain="$1"
	local subdomain="$2"
	local input
	input=$(dig "$subdomain"."$domain" +short) 
	local record_type=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
	echo "The subdomain $subdomain is a $record_type record and points to $input"
}

if [ "$#" -eq 1 ]; then
	dom_info "$1" "www"
	dom_info "$1" "lb-01"
	dom_info "$1" "web-01"
	dom_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	dom_info "$1" "$2"
fi
