#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
