#!/usr/bin/env bash
# install nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
