#!/usr/bin/env bash
# script configures a brand new Ubuntu machine

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/ a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com/redirected_page;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start
