#!/usr/bin/env bash
# Install nginx if not already installed

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server;/ a \\n\terror_page 404 /custom_404;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/ a \\n\tlocation = /custom_404 {\n\t\tinternal;\n\t\treturn 404 "Ceci n'\''est pas une page";\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
