#!/usr/bin/env bash
#  script adds custom header to web server

REDIRECT_301="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "30i $REDIRECT_301" /etc/nginx/sites-available/default

sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

sudo service nginx restart
