#!/usr/bin/env bash
# Backup script for mysql

# Check if password argument is provided
if [ -z "$1" ]; then
	echo "Error: Please provide the MySQL root password as an argument."
	exit 1
fi

# Define variables
MYSQL_USER="root"
MYSQL_PASSWORD="$1"
BACKUP_FILE="backup.sql"
TODAY=$(date +%d-%m-%Y)
ARCHIVE_FILE="$TODAY.tar.gz"

# Dump all databases
sudo mysqldump -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --all-databases > "$BACKUP_FILE"
# Create compressed archive
sudo tar -czvf "$ARCHIVE_FILE" "$BACKUP_FILE"
