#!/usr/bin/env bash
# script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM
cnt=0
while [ $cnt -le 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
