#!/usr/bin/env bash
# This script is displaying "Best School" 10 times.  If 9, say Hi!
count=0

while [ $count -lt 10 ]; do
	echo "Best School";
	if [ $count -eq 8 ]; then
		echo "Hi"
	fi
	((count++))
done

