#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements

cp /etc/hosts ~/hosts.bak
localhost_map='127.0.0.2 localhost'
fb_mapping='8.8.8.8 facebook.com'

echo "$localhost_map" >> ~/hosts.bak
echo "$fb_mapping" >> ~/hosts.bak
sudo cp ~/hosts.bak /etc/hosts
