#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements

cp /etc/hosts ~/hosts.bak
sed -i 's/127.*$/127.0.0.2 localhost/' ~/hosts.bak
sed -i 's/8.8.8.8 facebook.com/' ~/hosts.bak
sudo cp ~/hosts.bak /etc/hosts
