#!/usr/bin/env bash
# Update the user in nginx.conf from 'www-data' to 'nginx'
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Replace port '80' with port '8080' in the default site configuration file
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set the permissions of nginx.conf to read-only for owner and group
chmod 644 /etc/nginx/nginx.conf

# Stop the Apache2 service if it's running
pkill apache2

# Start the Nginx service with the 'nginx' user
sudo -u nginx service nginx start

